builds:
  - goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - "386"
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    binary: wstunnel
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm
      - goos: linux
        goarch: "386"
      - goos: darwin
        goarch: "386"
      - goos: freebsd
        goarch: "arm"
      - goos: freebsd
        goarch: "arm64"
    main: goreleaser.go
    hooks:
      #pre:
      #  - /bin/sh -c "if [ ! -e ./goreleaser.go ]; then echo -e 'package main\\\nfunc main() { }' > ./goreleaser.go ; fi"
      post:
        - ./.goreleaser_hook.sh "{{ .Arch }}" "{{ .Os }}" "{{ .Arm }}" "{{ .ProjectName }}"
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
