sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - docker build -t erebe/wstunnel .

script:
  - docker run --rm -ti -v $(pwd):/mnt erebe/wstunnel /bin/sh -c 'cp wstunnel /mnt'

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: AbS+BiwuYyXvcdpcHfdqQbug3I/PrFM4hl90RA1nnjLWWFnI03c0Em8EyTlFHp4FvJSDHmBXu2u6TD5QUVgo4YqKaOf6VqJCdbxvH0zubYBGhURtvCT9OGrl9emoUvpzsxLvFXminuVGGcfcn6Vk80wAszQhrDUNmzSDq8RwKLyjMx2xs/hmilz3+4oZ9HbFodho9v14VrboERgImxHBslR1/RrTCNKQAtOZzPhpxlWPEuQuD2Mx/8l+4TV8kBf61vKUncMrV/h6v8pR7aY78JuUXJszwKJwoeBwiBc22UaWzAP3ZSQEIKEJVpEH3q/JtYJcxutf8JnOdDCng/xN7n18GSN7YDrQe/AWVm0iS+keNx76zZrBKTW6sxUQRHhQq16wS3v5ve5yScL60TXKGcRGlmGbFwjGukFqj4MM/iK7JzfAqSyEwuh2S4IaBnaJj0AJW+608QMsO06AnCHIfi0lOtOLltEzBCAxj5ER+pTNrIq1jFE38hen0sTQknB16NmSKsleisbrZm2Vs32csGHt50TdG6keLmy94cTbXcvYsU2/LF6PApyYfL1rNFmSeUzVaqHamwemUOJXtUewveOcwkKz/bUA65movEeA3kJSv46r+sQ/3HQQLlLGw6wK2Yzc9sNf90OPBqBJ6ZJoAtBN2U1zIHoI4XW+RsKdURE=
  file: wstunnel
  on:
    tags: true
