[package]
name = "wstunnel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.5", features = ["derive"]}
url = "2.4.1"

reqwest = { version  = "0.11.20", features = ["stream", "trust-dns"] }
hyper = { version = "1.0.0-rc.4", features = ["client", "http2"] }
hyper-openssl = {version = "0.9.2", features = []}

tokio = { version = "1.32.0", features = ["full"] }

tracing = { version = "0.1.37", features = ["log"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "fmt", "local-time"] }
