[package]
name = "wstunnel"
version = "8.5.1"
edition = "2021"
repository = "https://github.com/erebe/wstunnel.git"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = { version = "0.8.6", features = [] }
anyhow = "1.0.75"
async-trait = "0.1.74"
base64 = "0.21.5"

bb8 = { version = "0.8", features = [] }
bytes = { version = "1.5.0", features = [] }
clap = { version = "4.4.11", features = ["derive", "env"] }
fast-socks5 = { version = "0.9.2", features = [] }
fastwebsockets = { version = "0.6.0", features = ["upgrade", "simd", "unstable-split"] }
futures-util = { version = "0.3.29" }
hickory-resolver = { version = "0.24.0", features = ["tokio", "dns-over-https-rustls", "dns-over-rustls"] }

hyper = { version = "1.0.1", features = ["client", "http1"] }
hyper-util = { version = "0.1.0", features = ["tokio"] }
http-body-util = { version = "0.1.0" }
jsonwebtoken = { version = "9.2.0", default-features = false }
log = "0.4.20"
nix = { version = "0.27.1", features = ["socket", "net", "uio"] }
once_cell = { version = "1.19.0", features = [] }
parking_lot = "0.12.1"
pin-project = "1"
notify = { version = "6.1.1", features = [] }

rustls-native-certs = { version = "0.7.0", features = [] }
rustls-pemfile = { version = "2.0.0", features = [] }
scopeguard = "1.2.0"
serde = { version = "1.0.193", features = ["derive"] }
socket2 = { version = "0.5.5", features = [] }
tokio = { version = "1.35.0", features = ["full"] }
tokio-rustls = { version = "0.24.1", features = ["tls12", "dangerous_configuration", "early-data"] }
tokio-stream = { version = "0.1.14", features = ["net"] }

tracing = { version = "0.1.40", features = ["log"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "fmt", "local-time"] }
url = "2.5.0"
urlencoding = "2.1.3"
uuid = { version = "1.6.1", features = ["v7", "serde"] }

[target.'cfg(not(target_family = "unix"))'.dependencies]
crossterm = { version = "0.27.0" }
tokio-util = { version = "0.7.10", features = ["io"] }

[target.'cfg(target_family = "unix")'.dependencies]
tokio-fd = "0.3.0"

[dev-dependencies]
testcontainers = "0.15.0"

[profile.release]
lto = "fat"
panic = "abort"
codegen-units = 1
opt-level = 3
debug = 1
