[package]
name = "wstunnel"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/erebe/wstunnel.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.5", features = ["derive"]}
url = "2.4.1"
anyhow = "1.0.75"

hyper = { version = "0.14.27", features = ["client", "runtime"] }
#fastwebsockets = { version = "0.4.4", features = ["upgrade"]}
fastwebsockets = { git = "https://github.com/mmastrac/fastwebsockets", branch = "split", features = ["upgrade", "simd"]}
libc = { version = "0.2.148", features = []}
once_cell = { version = "1.18.0", features = [] }
ahash = { version = "0.8.3",  features = []}
pin-project = "1"
scopeguard = "1.2.0"
uuid = { version = "1.4.1", features = ["v7", "serde"] }
jsonwebtoken = { version = "9.0.0",  default-features = false }
rustls-pemfile = { version = "1.0.3", features = [] }

rustls-native-certs = { version = "0.6.3", features = [] }
tokio = { version = "1.32.0", features = ["full"] }
tokio-rustls = { version = "0.24.1", features = ["tls12", "dangerous_configuration", "early-data"] }
tokio-stream = { version = "0.1.14", features = ["net"] }
fast-socks5 = { version = "0.9.1", features = [] }
futures-util = { version = "0.3.28" }

tracing = { version = "0.1.37", features = ["log"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "fmt", "local-time"] }
base64 = "0.21.4"
serde = { version = "1.0.188", features = ["derive"] }
log = "0.4.20"

[target.'cfg(target_family = "unix")'.dependencies]
tokio-fd = "0.3.0"


[profile.release]
lto = "fat"
panic = "abort"
codegen-units = 1
opt-level = 3

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.3.1"
# CI backends to support
ci = ["github"]
# The installers to generate for each app
installers = []
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-unknown-linux-gnu", "aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-pc-windows-msvc"]
# Publish jobs to run in CI
pr-run-mode = "skip"
