[build]
rustflags = ["--cfg", "uuid_unstable"]

#[target.'cfg(target_os = "linux")']
#rustflags = ["-C", "linker=ld.lld", "-C", "relocation-model=static", "-C", "strip=symbols", "--cfg", "uuid_unstable"]

#[build]
