name: Build bot

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.6.5'
        cabal-version: '3.0'
       
    - name: Build
      run: |
        docker build -t wstunnel .
        docker run --rm -v $(pwd):/data wstunnel /bin/cp wstunnel /data
        ./wstunnel

    - uses: actions/upload-artifact@v1
      with:
        name: wstunnel-linux-x64
        path: wstunnel
        
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      
    - name: Install stack
      run: |
        curl -sSL https://get.haskellstack.org/ | sh
        
    - name: Setup GHC
      run: |
        stack setup
        
    - name: Build
      run: |
        stack install
        
    - uses: actions/upload-artifact@v1
      with:
        name: wstunnel-windows-x64.exe
        path: C:\Users\runneradmin\AppData\Roaming\local\bin\wstunnel.exe
      
      
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
      
    - name: Install stack
      run: |
        curl -sSL https://get.haskellstack.org/ | sh
        
    - name: Setup GHC
      run: |
        stack setup
        
    - name: Build
      run: |
        stack install
        
    - uses: actions/upload-artifact@v1
      with:
        name: wstunnel-macos
        path: ~/.local\bin\wstunnel
