name: Haskell CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.6.5'
        cabal-version: '3.0'
       
    - name: Build
      run: |
        stack setup
        stack build
        
    - name: Run tests
      run: stack test
