name: Haskell CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.6.5'
        cabal-version: '3.0'
       
    - name: Build
      run: |
        docker build -t wstunnel .
        docker run --rm -v $(pwd):/data wstunnel /bin/cp wstunnel /data
        ./wstunnel

    - uses: actions/upload-artifact@v1
      with:
        name: wstunnel
        path: wstunnel
