name: Build for windows

on: [push]

jobs:
  build:

    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install stack
      run: |
        curl -sSL https://get.haskellstack.org/ | sh
