name: Build for windows

on: [push]

jobs:
  build:

    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install stack
      run: |
        curl -sSL https://get.haskellstack.org/ | sh

    - name: Setup GHC
      run: |
        /c/Users/runneradmin/.local/bin/stack setup

    - name: Build
      run: |
        /c/Users/runneradmin/.local/bin/stack install
